export enum ActionTypes {
  GET_LEADERBOARD = 'GET_LEADERBOARD',
  GET_LEADERBOARD_SUCCESS = 'GET_LEADERBOARD_SUCCESS',
  CHANGE_LEADERBOARD = 'CHANGE_LEADERBOARD',
  REDIRECT_TO_LEADERBORD = 'REDIRECT_TO_LEADERBOARD',
}
