export enum ActionTypes {
  GET_SITE_THEMES = 'GET_SITE_THEMES',
  SITE_THEMES_SET_STATE = 'SITE_THEMES_SET_STATE',

  GET_USER_THEMES = 'GET_USER_THEME',
  PUT_USER_THEME = 'PUT_USER_THEME',
  USER_THEME_SET_STATE = 'USER_THEME_SET_STATE',
}
