version: "3"
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    container_name: proxy_nginx
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./logs:/var/log/nginx/
  server-app:
    container_name: server-app
    build:
      context: ./api
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:newPassword@postgres:5432/athensdb
      NODE_ENV: development
      PORT: 5000
    ports:
      - "5000:5000"
    volumes:
      - ./shared:/var/www/shared
    restart: always
    networks:
      - awesome
  postgres:
    container_name: postgres
    image: postgres:12
    ports:
      - "5432:5432"
    volumes:
      - ./postgresdata:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: newPassword
      POSTGRES_DB: athensdb
    networks:
      - awesome
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:4.18
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 8080
    ports:
      - "8080:8080"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - awesome
  athens-game:
    container_name: athens-game
    build:
      context: .
      dockerfile: Dockerfile
    extra_hosts:
      - "athens-furry-eureka-04.ya-praktikum.tech:127.0.0.1"
    ports:
      - "7999:7999"
    environment:
      NODE_ENV: production

volumes:
  pgadmin-data:

networks:
  awesome:
    driver: bridge