export enum ActionTypes {
  GET_USER_PROFILE = 'GET_USER_PROFILE',
  GET_USER_PROFILE_SUCCESS = 'GET_USER_PROFILE_SUCCESS',
  CHANGE_USER_PROFILE = 'CHANGE_USER_PROFILE',
  CHANGE_PASSWORD = 'CHANGE_PASSWORD',
}
