export enum ActionTypes {
  CREATE_USER = 'CREATE_USER',
  CREATE_TOPIC = 'CREATE_TOPIC',
  CREATE_COMMENT = 'CREATE_COMMENT',
  CREATE_REPLY = 'CREATE_REPLY',

  CREATE_USER_SET_STATE = 'CREATE_USER_SET_STATE',
  CREATE_TOPIC_SET_STATE = 'CREATE_TOPIC_SET_STATE',
  CREATE_COMMENT_SET_STATE = 'CREATE_COMMENT_SET_STATE',
  CREATE_REPLY_SET_STATE = 'CREATE_REPLY_SET_STATE',

  GET_USERS = 'GET_USERS',
  GET_TOPICS = 'GET_TOPICS',
  GET_COMMENTS = 'GET_COMMENTS',
  GET_REPLIES = 'GET_REPLIES',

  GET_USERS_SET_STATE = 'GET_USERS_SET_STATE',
  GET_TOPICS_SET_STATE = 'GET_TOPICS_SET_STATE',
  GET_COMMENTS_SET_STATE = 'GET_COMMENTS_SET_STATE',
  GET_REPLIES_SET_STATE = 'GET_REPLIES_SET_STATE',
}
