export enum ActionTypes {
  CREATE_USER = 'CREATE_USER',
  CREATE_TOPIC = 'CREATE_TOPIC',
  CREATE_COMMENT = 'CREATE_COMMENT',
  CREATE_REPLY = 'CREATE_REPLY',

  CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS',
  CREATE_TOPIC_SUCCESS = 'CREATE_TOPIC_SUCCESS',
  CREATE_COMMENT_SUCCESS = 'CREATE_COMMENT_SUCCESS',
  CREATE_REPLY_SUCCESS = 'CREATE_REPLY_SUCCESS',

  GET_USERS = 'GET_USERS',
  GET_TOPICS = 'GET_TOPICS',
  GET_COMMENTS = 'GET_COMMENTS',
  GET_REPLIES = 'GET_REPLIES',

  GET_USERS_SUCCESS = 'GET_USERS_SUCCESS',
  GET_TOPICS_SUCCESS = 'GET_TOPICS_SUCCESS',
  GET_COMMENTS_SUCCESS = 'GET_COMMENTS_SUCCESS',
  GET_REPLIES_SUCCESS = 'GET_REPLIES_SUCCESS',
}
